version: "3.8"

services:
  chatgpt-bot:
    build: .
    container_name: chatgpt-bot
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY
      - TELEGRAM_BOT_TOKEN
      # optional webhook
      - WEBHOOK # public https address
      - WEBHOOK_ADDR=chatgpt-bot # container name
      - WEBHOOK_PORT # defaults to 8080
      # optional database
      - DATABASE_URL
      - ENCRYPTION_KEY
    volumes:
      - ./database:/chatgpt_bot/database # default sqlite db
      - ./logs:/chatgpt_bot/logs # bot logs
