version: "3.8"

services:
  chatgpt-bot:
    build: .
    container_name: chatgpt-bot
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY
      - TELEGRAM_BOT_TOKEN
    volumes:
      - ./database:/chatgpt_bot/database
      - ./logs:/chatgpt_bot/logs
