# app config
app = "chatgpt-telegram-bot"
primary_region = "ewr"  # Secaucus, NJ

# webhook
[http_service]
[env]
  WEBHOOK_ADDR = "0.0.0.0"
  WEBHOOK_PORT = "8080"
  WEBHOOK = "https://chatgpt-telegram-bot.fly.dev/"
